Sprint 3
uliasavi/middle.messenger.praktikum.yandex pull request #3
Opened 2022-12-24 12:21 UTC by uliasavi

2022-12-24 15:50 UTC, podlovchenko requested changes
Привет, сейчас падают пр чеки, необходимо добавить директорию dist в ignoreFiles для stylelint
Локально при обновлении страницы `Cannot GET /messenger`, по заданию
<img width="723" alt="Снимок экрана 2022-12-24 в 18 42 33" src="https://user-images.githubusercontent.com/22602747/209442922-021be4d5-8909-4a28-9067-f548d23c15b4.png">
Для авторизованного пользователя нет редиректа на страницу чатов
На странице редактирования профиля нет валидации данных
Нет возможности изменить аватар

2022-12-24 15:50 UTC, podlovchenko commented on src/components/chatsComponents/AddModal/AddModal.scss
> +    input{
Лучше использовать классы, а не теги
Статья на эту тему https://frontstuff.io/you-need-to-stop-targeting-tags-in-css

2022-12-24 15:50 UTC, podlovchenko commented on src/components/chatsComponents/AddModal/index.ts
> +    }) => void;
Можно использовать тип Event

2022-12-24 15:50 UTC, podlovchenko commented on src/components/chatsComponents/AddModal/index.ts
> +    });
Копирование излишне
```suggestion
    super(props);
```

2022-12-24 15:50 UTC, podlovchenko commented on src/components/chatsComponents/AddModal/index.ts
> +  }
Можно не указывать конструктор, если в нем только вызов родительского

2022-12-24 15:50 UTC, podlovchenko commented on src/utils/HTTPTransport.ts
> +  public post<Response = void>(path: string, data?: unknown): Promise<Response> {
Можно тип для data также определить через дженерик

2022-12-24 16:19 UTC, uliasavi commented on src/components/chatsComponents/AddModal/AddModal.scss
> +    input{
![image](https://user-images.githubusercontent.com/63160106/209443910-8229afd0-0e4b-4abd-a91d-3b2b0d10c53c.png)
привет, но у меня есть валидация на странице редактирования

2022-12-25 10:41 UTC, podlovchenko commented
Привет, на странице редактирования профиля не хватает валидации по регуляркам
<img width="600" alt="Снимок экрана 2022-12-25 в 13 36 32" src="https://user-images.githubusercontent.com/22602747/209464705-597502f1-a610-441b-90a1-b9a877d97c36.png">
Проблема с `Cannot GET` осталась
В server.js надо добавить отправку index.html
```
app.get('*', function(req, res) {
    res.sendFile(path.join(__dirname, '/dist/index.html'));
});
```

2022-12-25 14:07 UTC, podlovchenko approved these changes
Спасибо за оперативные правки, работу принимаю)

2022-12-25 14:07 UTC, podlovchenko commented on server.js
>  const PORT = 3000;
Часто требуется возможность получить порт снаружи скрипта, не изменяя код, это можно сделать через переменное окружение:
process.env.PORT || PORT;
https://nodejs.org/dist/latest-v8.x/docs/api/process.html

2022-12-26 15:26 UTC, merged